import fs from "node:fs";
import path from "node:path";
import type { RegistryManifest } from "../types.js";

/** Where the generated barrel lives, relative to the project's srcDir. */
export const BARREL_TARGET = "components/ui/mapcn/index.ts";

/**
 * Builds `components/ui/mapcn/index.ts` so a project can import everything it
 * has installed from `@/components/ui/mapcn`.
 *
 * `installed` is every component name in mapcn.json, not just the ones added in
 * this run -- the barrel is rewritten whole each time, so a partial list would
 * silently drop earlier components.
 */
export function barrelContent(manifest: RegistryManifest, installed: Array<string>): string {
  const names = new Set(installed);
  const specifiers = manifest.components
    .filter((entry) => names.has(entry.name))
    .flatMap((entry) => entry.barrelModules ?? []);

  return [
    "// Generated by mapcn-rn -- rewritten on every `add`. Edits here are lost.",
    "// Import the whole library from `@/components/ui/mapcn`.",
    "",
    ...[...new Set(specifiers)].sort().map((specifier) => `export * from "${specifier}";`),
    "",
  ].join("\n");
}

/** Writes the barrel. Returns true when the file changed. */
export function writeBarrel(
  projectRoot: string,
  srcDir: string,
  manifest: RegistryManifest,
  installed: Array<string>,
): boolean {
  const content = barrelContent(manifest, installed);
  const target = path.join(projectRoot, srcDir, BARREL_TARGET);
  if (fs.existsSync(target) && fs.readFileSync(target, "utf8") === content) return false;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, "utf8");
  return true;
}
