import fs from "node:fs";
import path from "node:path";
import manifest from "../registry.config";
import { APP_SRC, REPO_ROOT, SHARED_SRC } from "./paths";
import { extractExportedNames } from "./validate";
import { readFileNormalized, writeFileIfChanged } from "./fs-utils";

const API_OUT = path.join(REPO_ROOT, "packages/registry/api");

/**
 * Generates a git-diffable exported-symbol snapshot per component per
 * renderer. This is deliberately a lighter mechanism than a full ts-morph
 * AST diff (plan §5.3 anticipates that as a later refinement) -- it exists
 * so a PR that accidentally adds/removes a public export shows up as a
 * one-line diff in `packages/registry/api/*.api.md`, reviewable without
 * reading the component source. `registry:check`'s API-parity validator is
 * the thing that actually *fails* CI on drift; this is the human-readable
 * record of what shipped.
 */
function main() {
  fs.mkdirSync(API_OUT, { recursive: true });
  const written: Array<string> = [];

  for (const component of manifest.components) {
    if (component.source === "shared") {
      const names = new Set<string>();
      for (const file of component.files) {
        const absPath = path.join(SHARED_SRC, file.from);
        if (fs.existsSync(absPath)) extractExportedNames(readFileNormalized(absPath)).forEach((n) => names.add(n));
      }
      const outPath = path.join(API_OUT, `${component.name}.api.md`);
      if (writeFileIfChanged(outPath, renderSnapshot(component.name, "shared", [...names].sort()))) {
        written.push(path.relative(REPO_ROOT, outPath));
      }
      continue;
    }

    for (const renderer of component.renderers) {
      const names = new Set<string>();
      for (const file of component.filesByRenderer[renderer] ?? []) {
        if (file.internal) continue;
        const absPath = path.join(APP_SRC[renderer], file.path);
        if (fs.existsSync(absPath)) extractExportedNames(readFileNormalized(absPath)).forEach((n) => names.add(n));
      }
      const outPath = path.join(API_OUT, `${component.name}.${renderer}.api.md`);
      if (writeFileIfChanged(outPath, renderSnapshot(component.name, renderer, [...names].sort()))) {
        written.push(path.relative(REPO_ROOT, outPath));
      }
    }
  }

  written.forEach((f) => console.log(`  wrote ${f}`));
  console.log(`✓ ${manifest.components.length} component API snapshots up to date`);
}

function renderSnapshot(name: string, variant: string, exportedNames: Array<string>): string {
  const lines = [
    `# ${name} (${variant})`,
    "",
    "Generated by `pnpm registry:api` -- do not edit by hand.",
    "",
    ...(exportedNames.length ? exportedNames.map((n) => `- \`${n}\``) : ["_(no public exports)_"]),
  ];
  return lines.join("\n");
}

main();
