import path from "node:path";
import type { ComponentDefinition, RegistryManifest } from "./manifest";
import { APP_SRC, resolveAliasPath, SHARED_SRC } from "./paths";
import { readFileNormalized, writeFileIfChanged } from "./fs-utils";

const RENDERERS: Array<"maplibre" | "mapbox"> = ["maplibre", "mapbox"];

const GENERATED_HEADER_EXTENSIONS = new Set([".ts"]);

/**
 * Copies every `source: "shared"` component's files from packages/shared
 * into both apps' src/ trees. Returns the list of files actually written
 * (unchanged files are left untouched so mtimes/git status stay quiet).
 */
export function materializeSharedComponents(manifest: RegistryManifest): Array<string> {
  const written: Array<string> = [];
  for (const component of manifest.components) {
    if (component.source !== "shared") continue;
    for (const file of component.files) {
      const sourcePath = path.join(SHARED_SRC, file.from);
      const content = readFileNormalized(sourcePath);
      for (const renderer of RENDERERS) {
        const targetPath = path.join(APP_SRC[renderer], resolveAliasPath(file.to));
        if (writeFileIfChanged(targetPath, content)) {
          written.push(`apps/demo-${renderer}/src/${resolveAliasPath(file.to)}`);
        }
      }
    }
  }
  return written;
}

export function isGeneratedExtension(filePath: string): boolean {
  return GENERATED_HEADER_EXTENSIONS.has(path.extname(filePath));
}

export const BARREL_TARGET = "components/ui/mapcn/index.ts";

/**
 * Builds the `components/ui/mapcn/index.ts` barrel so consumers can import
 * everything from `@/components/ui/mapcn`. `modules` are import specifiers
 * relative to the barrel (or alias-absolute, for the location hook).
 *
 * The CLI generates the same file from whatever subset a project installed --
 * this version covers the full manifest, for the demo apps.
 */
export function barrelContent(modules: Array<string>): string {
  return [
    "// Generated by mapcn-rn. Re-exports every installed mapcn component so the",
    "// whole library can be imported from `@/components/ui/mapcn`.",
    "",
    ...modules.map((specifier) => `export * from "${specifier}";`),
    "",
  ].join("\n");
}

/**
 * Barrel specifiers for one component. Renderer-internal adapter files are
 * excluded on purpose: they expose different low-level primitives per renderer,
 * so re-exporting them would make the barrel's surface renderer-dependent.
 * Reach for those with a direct import from `@/components/ui/mapcn/map-renderer`.
 */
export function barrelModulesFor(component: ComponentDefinition): Array<string> {
  const targets =
    component.source === "shared"
      ? component.files.map((f) => resolveAliasPath(f.to))
      : (component.filesByRenderer.maplibre ?? [])
          .filter((f) => !f.internal)
          .map((f) => resolveAliasPath(f.to ?? `@ui/${path.basename(f.path)}`));

  return targets.filter(isBarrelModule).map((target) =>
    target.startsWith("components/ui/mapcn/")
      ? `./${path.basename(target).replace(/\.tsx?$/, "")}`
      : `@/${target.replace(/\.tsx?$/, "")}`,
  );
}

/**
 * Components (.tsx) and hooks are re-exported; type and utility modules
 * (map-types.ts, lib/mapcn/*.ts) are not.
 *
 * Each component already re-exports the types it takes -- map.tsx re-exports
 * MapProps, map-choropleth.tsx re-exports ChoroplethScale, and so on. Adding
 * their canonical modules to the barrel too would make those names ambiguous
 * across two `export *` sources, and ESM resolves an ambiguous star export by
 * silently exporting nothing. Import the primitives straight from
 * `@/lib/mapcn/types` when you need them.
 */
function isBarrelModule(target: string): boolean {
  if (target.startsWith("hooks/")) return true;
  return target.startsWith("components/ui/mapcn/") && target.endsWith(".tsx");
}

/** Every publicly-importable module in the manifest, as barrel specifiers. */
export function barrelModules(manifest: RegistryManifest): Array<string> {
  return [...new Set(manifest.components.flatMap(barrelModulesFor))].sort();
}

/** Writes the barrel into both demo apps. */
export function materializeBarrel(manifest: RegistryManifest): Array<string> {
  const content = barrelContent(barrelModules(manifest));
  const written: Array<string> = [];
  for (const renderer of RENDERERS) {
    if (writeFileIfChanged(path.join(APP_SRC[renderer], BARREL_TARGET), content)) {
      written.push(`apps/demo-${renderer}/src/${BARREL_TARGET}`);
    }
  }
  return written;
}
